title: Nadine Ahmed
description: Computer Sciences 
![Logo](https://github.com/Nadine516/Portfolio-/blob/main/assets/mee.jpg?raw=true)
Welcome to my portfolio! I am a CS student with a passion for AI, data engineering, frontend development, and cybersecurity.
theme: jekyll-theme-minimal
